- name: test gathering facts
  hosts: lab_equipment

  tasks:
    - name: print ios firmware currently running
      debug:
#        msg: "{{ ansible_facts['net_version'] }}"
        msg: "{{ ansible_facts['net_image'] }}"