- name: Show versions of Cat IOS
  hosts: sw1,sw2,sw3

  tasks:
    - name: print ios firmware currently running
      debug:
#        msg: "{{ ansible_facts['net_version'] }}"
        msg: "{{ ansible_facts['net_image'] }}"
